version: '3'
services:
    db:
        image: my-mysql
        build:
            context: ./
            dockerfile: Dockerfile-mysql
                    
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_USER=ponaszki
            - MYSQL_PASSWORD=ponaszki
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - net
    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
        networks:
            - net
    spring:
        image: spring
        build:
            context: ./
            dockerfile: Dockerfile-web
        depends_on: 
            - db
        ports: 
            - 8088:8080
        networks:
          - net
networks:
    net:
        driver: bridge
