CREATE TABLE IF NOT EXISTS `test`.`test` (`id` INT NOT NULL AUTO_INCREMENT, `message` VARCHAR(255) NULL, PRIMARY KEY (`id`));
CREATE TABLE IF NOT EXISTS `test`.`test2` (`id` INT NOT NULL AUTO_INCREMENT, `message` VARCHAR(255) NULL, PRIMARY KEY (`id`));
